version: "3.9"

services:

  reply-srv-app:
    build:
      context: ./reply-service
      dockerfile: Dockerfile
    container_name: reply-srv-app
    ports:
      - "7002:7002"
    restart: unless-stopped
    volumes:
      - ./reply-service:/usr/src/app
      - ./reply-service/node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - stackoverflow-redis
      - rabbitmq
    networks:
      - sw-net

  auth-srv-app:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-srv-app
    ports:
      - "7000:7000"
    restart: unless-stopped
    volumes:
      - ./auth-service:/usr/src/app
      - ./auth-service/node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - stackoverflow-redis
    networks:
      - sw-net

  posts-srv-app:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: posts-srv-app
    ports:
      - "7001:7001"
    restart: unless-stopped
    volumes:
      - ./post-service:/usr/src/app
      - ./post-service/node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - stackoverflow-redis
      - rabbitmq
    networks:
      - sw-net

  stackoverflow-redis:
    image: redis:latest
    container_name: stackoverflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    logging:
      driver: "none"
    networks:
      - sw-net

  redis-monitor:
    image: rediscommander/redis-commander:latest
    container_name: redis-monitor
    restart: unless-stopped
    ports:
      - "8001:8081"
    environment:
      - REDIS_HOSTS=local:stackoverflow-redis:6379
    networks:
      - sw-net

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - sw-net

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - sw-net

networks:
    sw-net:
      name: sw-net
      driver: bridge